# Generated by Django 3.2.11 on 2024-03-20 04:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, default='0000000000', max_length=30, null=True, region=None, verbose_name='phone number')),
                ('about_me', models.TextField(default='say something about yourself', verbose_name='about me')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='O', max_length=30, verbose_name='gender')),
                ('country', django_countries.fields.CountryField(default='IN', max_length=2, verbose_name='country')),
                ('city', models.CharField(default='Bengaluru', max_length=180, verbose_name='city')),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='profile photo')),
                ('followers', models.ManyToManyField(related_name='following', to='profiles.Profile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
    ]
